# Generated by Django 2.2.4 on 2020-05-03 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tmy_app', '0003_auto_20200429_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cityclass',
            options={'verbose_name_plural': 'City Classes'},
        ),
    ]
