# Generated by Django 2.2.4 on 2020-05-19 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tmy_app', '0006_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='userinfo',
            new_name='user_info',
        ),
    ]
