# Generated by Django 3.1.7 on 2021-04-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tmy_app', '0008_auto_20200520_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('city_name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='media')),
                ('description', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'City Classes',
            },
        ),
        migrations.DeleteModel(
            name='CityClass',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
