# Generated by Django 3.1.7 on 2021-04-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tmy_app', '0009_auto_20210403_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
    ]
